### ISSUE TITLE
Proc error

### ISSUE THREAD

**Issue by Deathlive** [sp4rkie/debian-on-termux#1]
When writing `ps` shows an error `Error, do this: mount -t prpc prpc /proc`
The folder itself `cd /proc` is empty.
How to fix this ?

**Comment by sp4rkie** [comment]
There unfortunately is a known issue in proot: https://github.com/termux/termux-packages/issues/1679
This is why `/proc` is not currently mounted in `$HOME/bin/enter_deb`.

If you nevertheless want mount  `/proc`  just add `-b /proc`

But in that case you should use a patched `proot package` as suggested by @xeffyr. You may hit #1679 otherwise.

**Comment by Deathlive** [comment]
@sp4rkie Very thanks )
Another small question, how can I add fish shell in default ?
When writing `chsh -s fish`, `Error chsh: PAM: System error`
Can I need something to change in the script `enter_deb`?

**Comment by sp4rkie** [comment]
just `apt install fish` and replacing `/bin/bash` by `/usr/bin/fish` in `enter_deb` should do the job. 

Using `chsh` hits some permission issues typical for this not-root environment. But it won't help much anyway since `/etc/passwd` isn't evaluated in our case.
