### ISSUE TITLE
Nmap,Bettercap - Wlan0 Permission denied

### ISSUE THREAD

**Issue by Deathlive** [sp4rkie/debian-on-termux#2]
So far, in Root there is a big problem, he does not see the Wlan0 and bluetooth adapters.
Nmap can be used without Root, but here Bettercap requires Root.
**If you could fix this problem, it would be perfect.**
![default](https://user-images.githubusercontent.com/29791715/31899519-d28b4e3a-b82c-11e7-9279-4627f65bca81.png)

**Comment by sp4rkie** [comment]
I know there are some inherent problems imposed by the underlying Android...

BTW: the same errors appear for `nmap` when running directly under `termux` as `root`.
And `bettercap` does not exist at all for termux at this time. 
Time will tell what we can do to run these applications requiring special permissions.

**Comment by Deathlive** [comment]
@sp4rkie The problem is that when you start enter_deb -0 -p, it does not get the access root.
But if you start with the **tsu** later **enter_deb -0 -p**, then everything will work.
whether you can correct enter_deb, so that when start to get Root access?(to getting roots without tsu )

**Comment by sp4rkie** [comment]
> when you start enter_deb -0 -p, it does not get the access root.

correct, because the OS simply does not grant root rights. The `-0` only *pretends* to be root to the invoked application. 
> start with the tsu later enter_deb -0 -p, then everything will work

correct, because on a rooted device `tsu` drops a root shell with all root OS permissions granted.

The problem is that `tsu` can't invoke other programs. It only spawns a shell. So I can't simply prepend `tsu` to `enter_deb`.
But there exists a `sudo` program for termux here: https://github.com/st42/termux-sudo
Did you try that already?

Is it possible to simply invoke `enter_deb` like this:
         sudo $HOME/bin/enter_deb
If that works I could  integrate `sudo` into `enter_deb`
I can't test that myself because I don't own a rooted device
