### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by bania789** [sp4rkie/debian-on-termux#24]
raded, 0 newly installed, 0 to remove and 0 not upgraded.
--2018-04-25 20:14:48--  http://http.debian.net/debian/pool/main/d/debootstrap/debootstrap_1.0.95.tar.gz
Resolving http.debian.net... 128.31.0.62, 5.153.231.4, 130.89.148.14, ...
Connecting to http.debian.net|128.31.0.62|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.95.tar.gz [following]
--2018-04-25 20:14:48--  http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.95.tar.gz
Resolving cdn-fastly.deb.debian.org... 151.101.12.204
Connecting to cdn-fastly.deb.debian.org|151.101.12.204|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-04-25 20:14:48 ERROR 404: Not Found.

tar: invalid magic
tar: short read
$ tail -F $HOME/deboot_debian/debootstrap/debootstrap.log
tail: can't open '/data/data/com.termux/files/home/deboot_debian/debootstrap/debootstrap.log': No such file or directory

**Comment by sp4rkie** [comment]
a new upstream version of debootstrap is available. Please retry with the current version of debian-on-termux.

**Comment by abinashdash17** [comment]
Same issue here. Failed at setup_device_simple() .

**Comment by abinashdash17** [comment]
Assuming this an debootstrap issue(because I successfully installed debian to my device before) , I tried older versions of debootstarp. 0.96 didn't work. So I tried [0.92](http://ftp.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.92~bpo9+1.tar.gz) . It's working fine for me(armhf and jessie). Anyone having this problem can try this until some real solution comes up.

**Comment by abinashdash17** [comment]
Also I would like to suggest adding the debootstrap tar packages(all versions which worked well with this script) to the debian-on-termux github repo so that the change in debian pool won't cause 404 errors here. The 0.93 and 0.95 versions are no longer available in main pool.

**Comment by abinashdash17** [comment]
And a request to those who have a copy of 0.93 and/or 0.95 version of debootstrap, please share it. One of those (or both) worked fine with debian-on-termux script. As far as I can remember, about 2 months ago this script worked flawlessly but now it's not.

**Comment by sp4rkie** [comment]
I now found a 0.95 version . It's already patched. Please rename the attached file by

`mv debootstrap-1.0.95.tgz.zip debootstrap-1.0.95.tgz` 

since *tgz attachments are not allowed here. Don't ask me why.
#
[debootstrap-1.0.95.tgz.zip](https://github.com/sp4rkie/debian-on-termux/files/1991333/debootstrap-1.0.95.tgz.zip)

**Comment by abinashdash17** [comment]
Thanks @sp4rkie. Users who want older versions which are unavailable at main pool(e.g 1.0.93 version), try [debian snapshot](http://snapshot.debian.org/package/debootstrap/). But using sp4rkie's attachment would be a better option for this particular problem as it is already patched.

**Comment by sp4rkie** [comment]
are there still any problems concerning this issue? In the meantime I would close the issue.
